name = "aoc25"
uuid = "6c36bf33-6705-4624-b931-7a3f99261966"
version = "0.1.0"
authors = ["max-de-rooij <54850292+max-de-rooij@users.noreply.github.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.6.3"
HiGHS = "1.20.1"
JuMP = "1.29.3"
Printf = "1.11.0"
TOML = "1.0.3"
Test = "1.11.0"
